before_script:
  - php -v
  - pecl install redis && docker-php-ext-enable redis
  - apt-get update && apt-get install -y --no-install-recommends unzip
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x composer.phar && mv composer.phar /usr/local/bin/composer
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex
  - composer config extra.symfony.require "$SYMFONY_VERSION"
  - composer update

test_8.0_5.4:
  image: php:8.0.2
  variables:
    SYMFONY_VERSION: '5.4'
  script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit

test_8.0_6.0:
  image: php:8.0.2
  variables:
    SYMFONY_VERSION: '6.0'
  script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - ./vendor/bin/phpunit
